### ISSUE TITLE
Check support for `/u` flag in installed PCRE library

### ISSUE THREAD

**Issue by jaswrks** [nylen/phpegjs#9]
Possible edge case.

On [this line](https://github.com/nylen/phpegjs/blob/75318482fff268190688676260a488783ab82a26/src/passes/generate-php.js#L797), should the generated PHP code check for UTF-8 support in the installed PCRE library before using the `/u` flag? I noticed that a check like this occurs in [`wp_check_invalid_utf8()`](https://github.com/WordPress/wordpress-develop/blob/311531a964e1d50153abde9ac005afcb1c372f46/src/wp-includes/formatting.php#L1125-L1128) so maybe a test like that one could be used here too, such as:

```php
static $utf8_pcre = null;

if ( ! isset( $utf8_pcre ) ) {
    $utf8_pcre = @preg_match( '/^./u', 'a' );
}
```

and then...

```php
if ( $utf8_pcre ) {
    preg_match_all('/./us', $input, $match);
} else {
    preg_match_all('/./s', $input, $match);
}
```

---

It's been a while since I've seen this occur in the wild, so I'm not sure how common it is for PCRE to be compiled without UTF-8 these days, but thought it was still worth mentioning. Related article here: https://chrisjean.com/unicode-support-on-centos-52-with-php-and-pcre/

**Comment by nylen** [comment]
The information in this issue is correct, but I think we can close it (and the related Gutenberg and WP core issues) because it is already handled correctly.

From the "Using the Parser" section of the readme:

> Note that the generated PHP parser will call `preg_match_all( '/./us', ... )` on the input string. This may be undesirable for projects that need to maintain compatibility with PCRE versions that are missing Unicode support (WordPress, for example). To avoid this call, split the input string into an array (one array element per UTF-8 character) and pass this array into `$parser->parse()` instead of the string input.

This is what Gutenberg does.  See:  https://github.com/WordPress/gutenberg/search?q=_gutenberg_utf8_split

This misconfiguration should be very uncommon, and even less common over time.  I tested with CentOS 6.9 and PCRE is compiled with full Unicode support.  So, as far as this individual project is concerned, I'm content to leave this as a possible, but documented, edge case, unless we can document it better or it starts causing problems.
